// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountLeaseState } from "./AccountLeaseState";
import type { RateLimitSnapshot } from "./RateLimitSnapshot";

export type AccountListEntry = { id: string, label: string | null, email: string | null, isActive: boolean, exhaustedUntilUnixSeconds: number | null, lastRateLimits: RateLimitSnapshot | null, leaseState: AccountLeaseState, };
