// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { MergeStrategy } from "./MergeStrategy";

export type ConfigEdit = {
/**
 * Dotted config path. Escape literal `.` or `\` inside a segment with `\`.
 */
keyPath: string, value: JsonValue, mergeStrategy: MergeStrategy, };
