// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "../AuthMode";
import type { Account } from "./Account";

export type GetAccountResponse = { account: Account | null, authMode: AuthMode | null, requiresOpenaiAuth: boolean, activeChatgptStoreAccountId: string | null, };
