// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetAccountParams = { 
/**
 * When `true`, requests a proactive token refresh before returning.
 *
 * In managed auth mode this triggers the normal refresh-token flow and the
 * RPC fails if the requested refresh fails. In external auth mode this
 * flag is ignored. Clients should refresh tokens themselves and call
 * `account/login/start` with `chatgptAuthTokens`.
 */
refreshToken: boolean, };
