// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoginAccountParams = { "type": "apiKey", apiKey: string, } | { "type": "chatgpt" } | { "type": "chatgptAuthTokens", 
/**
 * Access token (JWT) supplied by the client.
 * This token is used for backend API requests and email extraction.
 * Malformed tokens are rejected as invalid input.
 */
accessToken: string, 
/**
 * Workspace/account identifier supplied by the client.
 */
chatgptAccountId: string, 
/**
 * Optional plan type supplied by the client.
 *
 * When present, this value remains authoritative over JWT-derived plan
 * claims. When `null`, Codex attempts to derive the plan type from the
 * access-token claims. If the effective plan is missing, `unknown`, or
 * unsupported, the login request is rejected.
 */
chatgptPlanType?: string | null, };
