use sha2::Digest;
use sha2::Sha256;
use std::fmt::Write as _;
use std::fs;
use std::fs::OpenOptions;
use std::io::ErrorKind;
use std::path::Path;
use std::path::PathBuf;
use std::process::Command;

const PINNED_CURSOR_CLI_VERSION: &str = "2026.07.23-e383d2b";
const PINNED_CURSOR_CLI_SHA256: &str =
    "eed61c5224668c9236334c4c68936a16aecc37374b592f59e31eb50433817831";
const AGENT_SERVICE_TYPE_NAME: &str = "agent.v1.AgentService";
const DASHBOARD_SERVICE_TYPE_NAME: &str = "aiserver.v1.DashboardService";
const HEARTBEAT_INTERVAL_SECONDS: u64 = 5;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let proto_dir = manifest_dir.join("proto");
    let agent_service_proto = proto_dir.join("agent_service.proto");
    let dashboard_proto = proto_dir.join("dashboard.proto");
    let proto_files = [agent_service_proto.clone(), dashboard_proto.clone()];
    let src_dir = manifest_dir.join("src");
    let generated_agent_service_path = src_dir.join("agent.v1.rs");
    let generated_dashboard_path = src_dir.join("aiserver.v1.rs");
    let target_file = src_dir.join("proto.rs");

    let protoc = protoc_bin_vendored::protoc_bin_path()?;
    let protoc_include = protoc_bin_vendored::include_path()?;
    let mut prost_config = tonic_prost_build::Config::new();
    prost_config.protoc_executable(protoc);

    tonic_prost_build::configure()
        .build_client(true)
        .build_server(true)
        .emit_rerun_if_changed(false)
        .out_dir(&src_dir)
        .compile_with_config(
            prost_config,
            &proto_files,
            &[proto_dir, protoc_include],
        )?;

    let schema_sha256 = schema_sha256(&[
        ("agent_service.proto", &agent_service_proto),
        ("dashboard.proto", &dashboard_proto),
    ])?;
    let generated_agent_service = fs::read_to_string(&generated_agent_service_path)?;
    let generated_dashboard = fs::read_to_string(&generated_dashboard_path)?;
    let output = format!(
        "// @generated by examples/generate-proto.rs. Do not edit manually.\n\
         #![allow(clippy::large_enum_variant)]\n\n\
         pub const PINNED_CURSOR_CLI_VERSION: &str = {PINNED_CURSOR_CLI_VERSION:?};\n\
         pub const PINNED_CURSOR_CLI_SHA256: &str = {PINNED_CURSOR_CLI_SHA256:?};\n\
         pub const PINNED_SCHEMA_SHA256: &str = {schema_sha256:?};\n\
         pub const AGENT_SERVICE_TYPE_NAME: &str = {AGENT_SERVICE_TYPE_NAME:?};\n\
         pub const DASHBOARD_SERVICE_TYPE_NAME: &str = {DASHBOARD_SERVICE_TYPE_NAME:?};\n\
         pub const HEARTBEAT_INTERVAL_SECONDS: u64 = {HEARTBEAT_INTERVAL_SECONDS};\n\n\
         {generated_agent_service}\n\n\
         pub mod dashboard {{\n\
             {generated_dashboard}\n\
         }}"
    );

    publish_atomically(&target_file, output.as_bytes())?;
    fs::remove_file(generated_agent_service_path)?;
    fs::remove_file(generated_dashboard_path)?;
    Ok(())
}

fn schema_sha256(files: &[(&str, &Path)]) -> Result<String, Box<dyn std::error::Error>> {
    let mut hasher = Sha256::new();
    for (name, path) in files {
        let bytes = fs::read(path)?;
        hasher.update(name.as_bytes());
        hasher.update([0]);
        hasher.update((bytes.len() as u64).to_be_bytes());
        hasher.update(bytes);
    }
    Ok(hex_digest(hasher.finalize()))
}

fn hex_digest(digest: impl AsRef<[u8]>) -> String {
    let digest = digest.as_ref();
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in digest {
        write!(&mut hex, "{byte:02x}").expect("writing to String cannot fail");
    }
    hex
}

fn publish_atomically(path: &Path, contents: &[u8]) -> Result<(), Box<dyn std::error::Error>> {
    let staged_path = path.with_extension("rs.stage");
    fs::write(&staged_path, contents)?;
    let rustfmt_output = Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .arg("--config")
        .arg("imports_granularity=Item")
        .arg(&staged_path)
        .output()?;
    if !rustfmt_output.status.success() {
        return Err(format!(
            "rustfmt failed with status {}\nstdout:\n{}\nstderr:\n{}",
            rustfmt_output.status,
            String::from_utf8_lossy(&rustfmt_output.stdout),
            String::from_utf8_lossy(&rustfmt_output.stderr),
        )
        .into());
    }
    let staged_contents = fs::read(&staged_path)?;
    match fs::read(path) {
        Ok(current) if current == staged_contents => {
            fs::remove_file(staged_path)?;
            return Ok(());
        }
        Ok(_) => {}
        Err(error) if error.kind() == ErrorKind::NotFound => {}
        Err(error) => return Err(error.into()),
    }
    let staged_file = OpenOptions::new().read(true).open(&staged_path)?;
    staged_file.sync_all()?;
    fs::rename(staged_path, path)?;
    Ok(())
}
