pub mod api_bridge;
pub mod auth;
pub mod auth_env_telemetry;
pub mod provider_auth;
pub mod token_data;

mod device_code_auth;
mod pkce;
mod server;

pub use codex_client::BuildCustomCaTransportError as BuildLoginHttpClientError;
pub use codex_config::types::AuthCredentialsStoreMode;
pub use device_code_auth::DeviceCode;
pub use device_code_auth::complete_device_code_login;
pub use device_code_auth::request_device_code;
pub use device_code_auth::run_device_code_login;
pub use server::LoginServer;
pub use server::ServerOptions;
pub use server::ShutdownHandle;
pub use server::run_login_server;

// Merge-safety anchor: codex-login re-exports define the split auth surface
// consumed by login flows and tests after the auth crate extraction.
pub use api_bridge::auth_provider_from_auth;
pub use auth::AccountRateLimitRefreshOutcome;
pub use auth::AccountRateLimitRefreshRoster;
pub use auth::AccountRateLimitRefreshRosterStatus;
pub use auth::AccountSummary;
pub use auth::AccountUsageCache;
pub use auth::AuthConfig;
pub use auth::AuthDotJson;
pub use auth::AuthManager;
pub use auth::AuthManagerConfig;
pub use auth::AuthStore;
pub use auth::CLIENT_ID;
pub use auth::CODEX_API_KEY_ENV_VAR;
pub use auth::ChatgptAccountAuthResolution;
pub use auth::ChatgptAccountRefreshMode;
pub use auth::CodexAuth;
pub use auth::EXTERNAL_INVALID_ACCESS_TOKEN_MESSAGE;
pub use auth::EXTERNAL_SUPPORTED_CHATGPT_PLAN_REQUIRED_MESSAGE;
pub use auth::ExternalAuth;
pub use auth::ExternalAuthChatgptMetadata;
pub use auth::ExternalAuthLoginError;
pub use auth::ExternalAuthRefreshContext;
pub use auth::ExternalAuthRefreshReason;
pub use auth::ExternalAuthTokens;
pub use auth::OPENAI_API_KEY_ENV_VAR;
pub use auth::PreflightAuthState;
pub use auth::REFRESH_TOKEN_URL_OVERRIDE_ENV_VAR;
pub use auth::RefreshTokenError;
pub use auth::StoredAccount;
pub use auth::UNSUPPORTED_CHATGPT_PLAN_REMOVED_MESSAGE;
pub use auth::UnauthorizedRecovery;
pub use auth::UsageLimitAutoSwitchFallbackSelectionMode;
pub use auth::UsageLimitAutoSwitchRequest;
pub use auth::UsageLimitAutoSwitchSelectionScope;
pub use auth::default_client;
pub use auth::enforce_login_restrictions;
pub use auth::load_auth_preflight_state;
pub use auth::load_auth_store;
pub use auth::login_with_api_key;
pub use auth::logout;
pub use auth::read_openai_api_key_from_env;
pub use auth::save_auth;
pub use auth::usage_limit_auto_switch_removes_plan_type;
pub use auth_env_telemetry::AuthEnvTelemetry;
pub use auth_env_telemetry::collect_auth_env_telemetry;
pub use codex_app_server_protocol::AuthMode;
pub use provider_auth::auth_manager_for_provider;
pub use provider_auth::required_auth_manager_for_provider;
pub use token_data::TokenData;
