// @generated by examples/generate-proto.rs. Do not edit manually.
#![allow(clippy::large_enum_variant)]

pub const PINNED_CURSOR_CLI_VERSION: &str = "2026.07.23-e383d2b";
pub const PINNED_CURSOR_CLI_SHA256: &str =
    "eed61c5224668c9236334c4c68936a16aecc37374b592f59e31eb50433817831";
pub const PINNED_SCHEMA_SHA256: &str =
    "9117b3cfd5c5f903ec42e74c81312d9392dbb09b6fedc4be429f6b18437a931d";
pub const AGENT_SERVICE_TYPE_NAME: &str = "agent.v1.AgentService";
pub const HEARTBEAT_INTERVAL_SECONDS: u64 = 5;

// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClientHeartbeat {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentClientMessage {
    #[prost(oneof = "agent_client_message::Message", tags = "1, 2, 7")]
    pub message: ::core::option::Option<agent_client_message::Message>,
}
/// Nested message and enum types in `AgentClientMessage`.
pub mod agent_client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        RunRequest(super::AgentRunRequest),
        #[prost(message, tag = "2")]
        ExecClientMessage(super::ExecClientMessage),
        #[prost(message, tag = "7")]
        ClientHeartbeat(super::ClientHeartbeat),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentServerMessage {
    #[prost(oneof = "agent_server_message::Message", tags = "1, 2, 3, 4, 5, 7")]
    pub message: ::core::option::Option<agent_server_message::Message>,
}
/// Nested message and enum types in `AgentServerMessage`.
pub mod agent_server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        InteractionUpdate(super::InteractionUpdate),
        #[prost(message, tag = "2")]
        ExecServerMessage(super::ExecServerMessage),
        #[prost(message, tag = "3")]
        ConversationCheckpointUpdate(super::UnsupportedAgentServerMessage),
        #[prost(message, tag = "4")]
        KvServerMessage(super::UnsupportedAgentServerMessage),
        #[prost(message, tag = "5")]
        ExecServerControlMessage(super::UnsupportedAgentServerMessage),
        #[prost(message, tag = "7")]
        InteractionQuery(super::UnsupportedAgentServerMessage),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnsupportedAgentServerMessage {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentRunRequest {
    #[prost(message, optional, tag = "1")]
    pub conversation_state: ::core::option::Option<ConversationStateStructure>,
    #[prost(message, optional, tag = "2")]
    pub action: ::core::option::Option<ConversationAction>,
    #[prost(message, optional, tag = "3")]
    pub model_details: ::core::option::Option<ModelDetails>,
    #[prost(message, optional, tag = "4")]
    pub mcp_tools: ::core::option::Option<McpTools>,
    #[prost(string, optional, tag = "5")]
    pub conversation_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "6")]
    pub mcp_file_system_options: ::core::option::Option<McpFileSystemOptions>,
    #[prost(message, optional, tag = "7")]
    pub skill_options: ::core::option::Option<SkillOptions>,
    #[prost(string, optional, tag = "8")]
    pub custom_system_prompt: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "9")]
    pub requested_model: ::core::option::Option<RequestedModel>,
    #[prost(bool, optional, tag = "10")]
    pub suggest_next_prompt: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "11")]
    pub subagent_type_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "12")]
    pub exclude_workspace_context: ::core::option::Option<bool>,
    #[prost(string, optional, tag = "13")]
    pub harness: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConversationStateStructure {
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub root_prompt_messages_json: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, repeated, tag = "4")]
    pub pending_tool_calls: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "6")]
    pub summary: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "7")]
    pub plan: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", repeated, tag = "8")]
    pub turns: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(enumeration = "AgentMode", optional, tag = "10")]
    pub mode: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConversationTurnStructure {
    #[prost(oneof = "conversation_turn_structure::Turn", tags = "1")]
    pub turn: ::core::option::Option<conversation_turn_structure::Turn>,
}
/// Nested message and enum types in `ConversationTurnStructure`.
pub mod conversation_turn_structure {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Turn {
        #[prost(message, tag = "1")]
        AgentConversationTurn(super::AgentConversationTurnStructure),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentConversationTurnStructure {
    #[prost(bytes = "vec", tag = "1")]
    pub user_message: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub steps: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "3")]
    pub request_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub encrypted_model: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, optional, tag = "5")]
    pub dynamic_tool_count: ::core::option::Option<u32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversationStep {
    #[prost(oneof = "conversation_step::Message", tags = "1, 2")]
    pub message: ::core::option::Option<conversation_step::Message>,
}
/// Nested message and enum types in `ConversationStep`.
pub mod conversation_step {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        AssistantMessage(super::AssistantMessage),
        #[prost(message, tag = "2")]
        ToolCall(super::ToolCall),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssistantMessage {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversationAction {
    #[prost(oneof = "conversation_action::Action", tags = "1")]
    pub action: ::core::option::Option<conversation_action::Action>,
}
/// Nested message and enum types in `ConversationAction`.
pub mod conversation_action {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Action {
        #[prost(message, tag = "1")]
        UserMessageAction(super::UserMessageAction),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserMessageAction {
    #[prost(message, optional, tag = "1")]
    pub user_message: ::core::option::Option<UserMessage>,
    #[prost(message, optional, tag = "2")]
    pub request_context: ::core::option::Option<RequestContext>,
    #[prost(bool, optional, tag = "3")]
    pub send_to_interaction_listener: ::core::option::Option<bool>,
    #[prost(message, repeated, tag = "4")]
    pub prepend_user_messages: ::prost::alloc::vec::Vec<UserMessage>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserMessage {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelDetails {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub display_model_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub display_name_short: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "6")]
    pub aliases: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "7")]
    pub max_mode: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestedModel {
    #[prost(string, tag = "1")]
    pub model_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub max_mode: bool,
    #[prost(message, repeated, tag = "3")]
    pub parameters: ::prost::alloc::vec::Vec<requested_model::ModelParameterValue>,
    #[prost(bool, tag = "7")]
    pub built_in_model: bool,
    #[prost(bool, tag = "8")]
    pub is_variant_string_representation: bool,
}
/// Nested message and enum types in `RequestedModel`.
pub mod requested_model {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct ModelParameterValue {
        #[prost(string, tag = "1")]
        pub id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub value: ::prost::alloc::string::String,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpToolDefinition {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub input_schema: ::core::option::Option<::prost_types::Struct>,
    #[prost(string, tag = "4")]
    pub provider_identifier: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub tool_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "6")]
    pub input_schema_json: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpTools {
    #[prost(message, repeated, tag = "1")]
    pub mcp_tools: ::prost::alloc::vec::Vec<McpToolDefinition>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpFileSystemOptions {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SkillOptions {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CursorRuleTypeGlobal {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CursorRuleTypeFileGlobs {
    #[prost(string, repeated, tag = "1")]
    pub globs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CursorRuleTypeAgentFetched {
    #[prost(string, tag = "1")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CursorRuleTypeManuallyAttached {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CursorRuleType {
    #[prost(oneof = "cursor_rule_type::Type", tags = "1, 2, 3, 4")]
    pub r#type: ::core::option::Option<cursor_rule_type::Type>,
}
/// Nested message and enum types in `CursorRuleType`.
pub mod cursor_rule_type {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Type {
        #[prost(message, tag = "1")]
        Global(super::CursorRuleTypeGlobal),
        #[prost(message, tag = "2")]
        FileGlobbed(super::CursorRuleTypeFileGlobs),
        #[prost(message, tag = "3")]
        AgentFetched(super::CursorRuleTypeAgentFetched),
        #[prost(message, tag = "4")]
        ManuallyAttached(super::CursorRuleTypeManuallyAttached),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CursorRule {
    #[prost(string, tag = "1")]
    pub full_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub r#type: ::core::option::Option<CursorRuleType>,
    #[prost(enumeration = "CursorRuleSource", tag = "4")]
    pub source: i32,
    #[prost(string, repeated, tag = "7")]
    pub environments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "8")]
    pub disabled_environments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "13")]
    pub scoped_to: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "14")]
    pub frontmatter: ::prost::alloc::string::String,
    #[prost(bool, optional, tag = "15")]
    pub is_required: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestContext {
    #[prost(message, repeated, tag = "2")]
    pub rules: ::prost::alloc::vec::Vec<CursorRule>,
    #[prost(bool, optional, tag = "17")]
    pub web_search_enabled: ::core::option::Option<bool>,
    #[prost(message, optional, tag = "18")]
    pub skill_options: ::core::option::Option<SkillOptions>,
    #[prost(message, optional, tag = "23")]
    pub mcp_file_system_options: ::core::option::Option<McpFileSystemOptions>,
    #[prost(bool, optional, tag = "24")]
    pub web_fetch_enabled: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "32")]
    pub supports_mcp_auth: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "36")]
    pub mcp_info_complete: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "39")]
    pub rules_info_complete: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "40")]
    pub env_info_complete: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "41")]
    pub repository_info_complete: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "42")]
    pub custom_subagents_info_complete: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "43")]
    pub agent_skills_info_complete: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "44")]
    pub mcp_file_system_info_complete: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "45")]
    pub git_status_info_complete: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "50")]
    pub search_conversations_enabled: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestContextArgs {
    #[prost(string, optional, tag = "2")]
    pub notes_session_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub workspace_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub read_only_pinned_tree_sha: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub read_only_plugin_cache_root: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "7")]
    pub use_cached: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestContextResult {
    #[prost(oneof = "request_context_result::Result", tags = "1, 2, 3")]
    pub result: ::core::option::Option<request_context_result::Result>,
}
/// Nested message and enum types in `RequestContextResult`.
pub mod request_context_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::RequestContextSuccess),
        #[prost(message, tag = "2")]
        Error(super::RequestContextError),
        #[prost(message, tag = "3")]
        Rejected(super::RequestContextRejected),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestContextSuccess {
    #[prost(message, optional, tag = "1")]
    pub request_context: ::core::option::Option<RequestContext>,
    #[prost(bool, optional, tag = "2")]
    pub served_from_disk_cache: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestContextError {
    #[prost(string, tag = "1")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestContextRejected {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SmartModeApproval {
    #[prost(string, tag = "1")]
    pub request_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpArgs {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(map = "string, message", tag = "2")]
    pub args: ::std::collections::HashMap<::prost::alloc::string::String, ::prost_types::Value>,
    #[prost(string, tag = "3")]
    pub tool_call_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub provider_identifier: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub tool_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub smart_mode_approval: ::core::option::Option<SmartModeApproval>,
    #[prost(bool, tag = "7")]
    pub smart_mode_approval_only: bool,
    #[prost(bool, tag = "8")]
    pub skip_approval: bool,
    #[prost(string, tag = "9")]
    pub server_identifier: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpResult {
    #[prost(oneof = "mcp_result::Result", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub result: ::core::option::Option<mcp_result::Result>,
}
/// Nested message and enum types in `McpResult`.
pub mod mcp_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::McpSuccess),
        #[prost(message, tag = "2")]
        Error(super::McpError),
        #[prost(message, tag = "3")]
        Rejected(super::McpRejected),
        #[prost(message, tag = "4")]
        PermissionDenied(super::McpPermissionDenied),
        #[prost(message, tag = "5")]
        ToolNotFound(super::McpToolNotFound),
        #[prost(message, tag = "6")]
        ServerNotFound(super::McpServerNotFound),
        #[prost(message, tag = "7")]
        Approved(super::McpApproved),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpApproved {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpToolNotFound {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub available_tools: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpServerNotFound {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub available_servers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpTextContent {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpImageContent {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub mime_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpToolResultContentItem {
    #[prost(oneof = "mcp_tool_result_content_item::Content", tags = "1, 2")]
    pub content: ::core::option::Option<mcp_tool_result_content_item::Content>,
}
/// Nested message and enum types in `McpToolResultContentItem`.
pub mod mcp_tool_result_content_item {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Content {
        #[prost(message, tag = "1")]
        Text(super::McpTextContent),
        #[prost(message, tag = "2")]
        Image(super::McpImageContent),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpSuccess {
    #[prost(message, repeated, tag = "1")]
    pub content: ::prost::alloc::vec::Vec<McpToolResultContentItem>,
    #[prost(bool, tag = "2")]
    pub is_error: bool,
    #[prost(message, optional, tag = "3")]
    pub structured_content: ::core::option::Option<::prost_types::Struct>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpError {
    #[prost(string, tag = "1")]
    pub error: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpRejected {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_readonly: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpPermissionDenied {
    #[prost(string, tag = "1")]
    pub error: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_readonly: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct McpToolError {
    #[prost(string, tag = "1")]
    pub error: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub read_tool_def_reminder: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpToolResult {
    #[prost(oneof = "mcp_tool_result::Result", tags = "1, 2, 3, 4")]
    pub result: ::core::option::Option<mcp_tool_result::Result>,
}
/// Nested message and enum types in `McpToolResult`.
pub mod mcp_tool_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::McpSuccess),
        #[prost(message, tag = "2")]
        Error(super::McpToolError),
        #[prost(message, tag = "3")]
        Rejected(super::McpRejected),
        #[prost(message, tag = "4")]
        PermissionDenied(super::McpPermissionDenied),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct McpToolCall {
    #[prost(message, optional, tag = "1")]
    pub args: ::core::option::Option<McpArgs>,
    #[prost(message, optional, tag = "2")]
    pub result: ::core::option::Option<McpToolResult>,
    #[prost(string, optional, tag = "3")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolCall {
    #[prost(string, optional, tag = "57")]
    pub tool_call_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(oneof = "tool_call::Tool", tags = "15")]
    pub tool: ::core::option::Option<tool_call::Tool>,
}
/// Nested message and enum types in `ToolCall`.
pub mod tool_call {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Tool {
        #[prost(message, tag = "15")]
        McpToolCall(super::McpToolCall),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecServerMessage {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(string, tag = "15")]
    pub exec_id: ::prost::alloc::string::String,
    #[prost(
        oneof = "exec_server_message::Message",
        tags = "2, 3, 4, 5, 7, 8, 9, 10, 11, 14, 16, 17, 18, 20, 21, 22, 23, 27, 28, 29, 30, 31, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54"
    )]
    pub message: ::core::option::Option<exec_server_message::Message>,
}
/// Nested message and enum types in `ExecServerMessage`.
pub mod exec_server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "2")]
        ShellArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "3")]
        WriteArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "4")]
        DeleteArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "5")]
        GrepArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "7")]
        ReadArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "8")]
        LsArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "9")]
        DiagnosticsArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "10")]
        RequestContextArgs(super::RequestContextArgs),
        #[prost(message, tag = "11")]
        McpArgs(super::McpArgs),
        #[prost(message, tag = "14")]
        ShellStreamArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "16")]
        BackgroundShellSpawnArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "17")]
        ListMcpResourcesExecArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "18")]
        ReadMcpResourceExecArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "20")]
        FetchArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "21")]
        RecordScreenArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "22")]
        ComputerUseArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "23")]
        WriteShellStdinArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "27")]
        ExecuteHookArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "28")]
        SubagentArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "29")]
        RedactedReadArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "30")]
        ForceBackgroundShellArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "31")]
        ForceBackgroundSubagentArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "36")]
        McpStateExecArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "37")]
        SubagentAwaitArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "38")]
        SmartModeClassifierArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "40")]
        CanvasDiagnosticsArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "41")]
        ShellAllowlistPrecheckArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "42")]
        McpAllowlistPrecheckArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "43")]
        WebFetchAllowlistPrecheckArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "44")]
        GitDiffRequest(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "45")]
        PiReadArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "46")]
        PiBashArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "47")]
        PiEditArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "48")]
        PiWriteArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "49")]
        PiGrepArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "50")]
        PiFindArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "51")]
        PiLsArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "52")]
        MiniSweAgentBashArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "53")]
        ConversationSearchArgs(super::UnsupportedExecServerMessage),
        #[prost(message, tag = "54")]
        AgentStoreConflictArgs(super::UnsupportedExecServerMessage),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnsupportedExecServerMessage {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecClientMessage {
    #[prost(uint32, tag = "1")]
    pub id: u32,
    #[prost(string, tag = "15")]
    pub exec_id: ::prost::alloc::string::String,
    #[prost(int32, optional, tag = "39")]
    pub local_execution_time_ms: ::core::option::Option<i32>,
    #[prost(oneof = "exec_client_message::Message", tags = "10, 11")]
    pub message: ::core::option::Option<exec_client_message::Message>,
}
/// Nested message and enum types in `ExecClientMessage`.
pub mod exec_client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "10")]
        RequestContextResult(super::RequestContextResult),
        #[prost(message, tag = "11")]
        McpResult(super::McpResult),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InteractionUpdate {
    #[prost(
        oneof = "interaction_update::Message",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22"
    )]
    pub message: ::core::option::Option<interaction_update::Message>,
}
/// Nested message and enum types in `InteractionUpdate`.
pub mod interaction_update {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        TextDelta(super::TextDeltaUpdate),
        #[prost(message, tag = "2")]
        ToolCallStarted(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "3")]
        ToolCallCompleted(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "4")]
        ThinkingDelta(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "5")]
        ThinkingCompleted(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "6")]
        UserMessageAppended(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "7")]
        PartialToolCall(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "8")]
        TokenDelta(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "9")]
        Summary(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "10")]
        SummaryStarted(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "11")]
        SummaryCompleted(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "12")]
        ShellOutputDelta(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "13")]
        Heartbeat(super::HeartbeatUpdate),
        #[prost(message, tag = "14")]
        TurnEnded(super::TurnEndedUpdate),
        #[prost(message, tag = "15")]
        ToolCallDelta(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "16")]
        StepStarted(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "17")]
        StepCompleted(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "18")]
        PromptSuggestion(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "19")]
        PostRequestPrompt(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "20")]
        ActiveBranchChange(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "21")]
        FeedbackRequest(super::UnsupportedInteractionUpdate),
        #[prost(message, tag = "22")]
        ResponseComparison(super::UnsupportedInteractionUpdate),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnsupportedInteractionUpdate {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TextDeltaUpdate {
    #[prost(string, tag = "1")]
    pub text: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HeartbeatUpdate {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TurnEndedUpdate {
    #[prost(int64, optional, tag = "1")]
    pub input_tokens: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "2")]
    pub output_tokens: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "3")]
    pub cache_read_tokens: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "4")]
    pub cache_write_tokens: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "5")]
    pub reasoning_tokens: ::core::option::Option<i64>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AgentMode {
    Unspecified = 0,
}
impl AgentMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AGENT_MODE_UNSPECIFIED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AGENT_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CursorRuleSource {
    Unspecified = 0,
    Team = 1,
    User = 2,
}
impl CursorRuleSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "CURSOR_RULE_SOURCE_UNSPECIFIED",
            Self::Team => "CURSOR_RULE_SOURCE_TEAM",
            Self::User => "CURSOR_RULE_SOURCE_USER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CURSOR_RULE_SOURCE_UNSPECIFIED" => Some(Self::Unspecified),
            "CURSOR_RULE_SOURCE_TEAM" => Some(Self::Team),
            "CURSOR_RULE_SOURCE_USER" => Some(Self::User),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod agent_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    #[derive(Debug, Clone)]
    pub struct AgentServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AgentServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AgentServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AgentServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                    http::Request<tonic::body::Body>,
                    Response = http::Response<
                        <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                    >,
                >,
            <T as tonic::codegen::Service<http::Request<tonic::body::Body>>>::Error:
                Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AgentServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn run(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::AgentClientMessage>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::AgentServerMessage>>,
            tonic::Status,
        > {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::unknown(format!("Service was not ready: {}", e.into()))
            })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/agent.v1.AgentService/Run");
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("agent.v1.AgentService", "Run"));
            self.inner.streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod agent_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AgentServiceServer.
    #[async_trait]
    pub trait AgentService: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the Run method.
        type RunStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::AgentServerMessage, tonic::Status>,
            > + std::marker::Send
            + 'static;
        async fn run(
            &self,
            request: tonic::Request<tonic::Streaming<super::AgentClientMessage>>,
        ) -> std::result::Result<tonic::Response<Self::RunStream>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct AgentServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AgentServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(inner: T, interceptor: F) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AgentServiceServer<T>
    where
        T: AgentService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/agent.v1.AgentService/Run" => {
                    #[allow(non_camel_case_types)]
                    struct RunSvc<T: AgentService>(pub Arc<T>);
                    impl<T: AgentService> tonic::server::StreamingService<super::AgentClientMessage> for RunSvc<T> {
                        type Response = super::AgentServerMessage;
                        type ResponseStream = T::RunStream;
                        type Future =
                            BoxFuture<tonic::Response<Self::ResponseStream>, tonic::Status>;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::AgentClientMessage>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut =
                                async move { <T as AgentService>::run(&inner, request).await };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RunSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => Box::pin(async move {
                    let mut response = http::Response::new(tonic::body::Body::default());
                    let headers = response.headers_mut();
                    headers.insert(
                        tonic::Status::GRPC_STATUS,
                        (tonic::Code::Unimplemented as i32).into(),
                    );
                    headers.insert(
                        http::header::CONTENT_TYPE,
                        tonic::metadata::GRPC_CONTENT_TYPE,
                    );
                    Ok(response)
                }),
            }
        }
    }
    impl<T> Clone for AgentServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "agent.v1.AgentService";
    impl<T> tonic::server::NamedService for AgentServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
