// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollabAgentActivityKind } from "./CollabAgentActivityKind";

export type CollabAgentActivity = { 
/**
 * Category of the most recent observed progress signal for the agent.
 */
kind: CollabAgentActivityKind, 
/**
 * Short, user-facing summary of the observed activity.
 */
summary: string, 
/**
 * Unix timestamp in seconds when the activity was observed.
 */
occurred_at: bigint, };
