// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMode } from "./AuthMode";

export type GetAuthStatusResponse = { 
/**
 * Compatibility-only auth mode summary. Use `account/read` for the
 * authoritative auth/account surface.
 */
authMethod: AuthMode | null, 
/**
 * Deprecated compatibility field. Always `None`.
 */
authToken: string | null, requiresOpenaiAuth: boolean | null, };
