// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetAuthStatusParams = { 
/**
 * Deprecated compatibility flag.
 *
 * Accepted on the wire for legacy clients, but ignored. `getAuthStatus`
 * never returns auth tokens; use `account/read` for authoritative
 * auth/account state.
 */
includeToken: boolean | null, 
/**
 * When `true`, requests the legacy best-effort refresh path before
 * returning compatibility status.
 */
refreshToken: boolean | null, };
